### ISSUE TITLE
Add button to expand all links?

### ISSUE THREAD

**Issue by robmarkcole** [satellite-image-deep-learning/techniques#49]
It would be nice to hit a button and expand all links, so the page could be searched without needing to dive into the raw markdown

**Comment by Spiruel** [comment]
I don't think you can have javascript buttons on Github markdowns, but perhaps a bookmarklet would be a good solution?

Something like this would work, as long as the elements to be expanded can be filtered to the details elements in the markdown.

```
javascript:(function() {
  var detailsElements = document.getElementsByTagName('details');
  for (var i = 0; i < detailsElements.length; i++) {
    if (!detailsElements[i].hasAttribute('open')) {
      detailsElements[i].setAttribute('open', '');
    }
  }
})();
```

**Comment by robmarkcole** [comment]
Could you make a fork and try it out?

**Comment by robmarkcole** [comment]
Another option to reformat is to return all material out of the drop downs.
Format would be:
- Introductions and images
- Link to later section where links live

**Comment by robmarkcole** [comment]
Just removed the drop downs
