### ISSUE TITLE
dB scale of SAR images in SEN1-2

### ISSUE THREAD

**Issue by denisaqosja** [satellite-image-deep-learning/techniques#62]
Hello!  I want to convert the optical images of SEN1-2 to grayscale and then to dB scale. However, using just the dB formula (20*log10) gives much brighter images than the SAR ones. 

Can you please describe how was the dB scale of SAR images calculated?

**Comment by robmarkcole** [comment]
Please can you ask these kind of questions on the Discord at https://www.satellite-image-deep-learning.com/p/discord
Thanks
